# D̷E̷D̷S̷E̷C̷ Decorations (Purple / Modern)

general {
  border_size = 2
  gaps_in = 4
  gaps_out = 8

  col.active_border = rgba(B44Affcc) rgba(7B2FBEcc) 135deg
  col.inactive_border = rgba(B44Aff22) rgba(7B2FBE22) 135deg
}

decoration {
  rounding = 10

  active_opacity = 1.0
  inactive_opacity = 0.90
  fullscreen_opacity = 1.0

  dim_inactive = true
  dim_strength = 0.12
  dim_special = 0.8

  shadow {
    enabled = true
    range = 10
    render_power = 3
    color = rgba(B44Aff30)
    color_inactive = rgba(7B2FBE15)
    offset = 0, 4
  }

  blur {
    enabled = true
    size = 10
    passes = 4
    new_optimizations = true
    xray = true
    ignore_opacity = true
    special = true
    popups = true
    noise = 0.015
    contrast = 1.1
    brightness = 0.8
  }
}

group {
  col.border_active = rgba(B44Affcc)
  col.border_inactive = rgba(7B2FBE33)

  groupbar {
    col.active = rgba(B44Affcc)
    col.inactive = rgba(7B2FBE33)
    enabled = true
  }
}
