# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
# windowrule = opacity 1.0 override 1.0 override, match:class ^(zen)$
windowrule = workspace special:silent, match:class ^(asm-gui)$
windowrule = opacity 1.0 override 1.0 override, match:title (.*YouTube.*)

# Default workspaces
windowrule = workspace 3, match:class ^(discord)$
windowrule = workspace 4, match:class ^(com\.obsproject\.Studio)$
windowrule = workspace 4, match:title ^(Arctis Sound Manager)$
windowrule = workspace 4, match:class ^(org\.rncbc\.qpwgraph)$
